### ISSUE TITLE
Extreme momentum values created in boundary file

### ISSUE THREAD

**Issue by ForTozs** [powellb/seapy#27]
I've created a climatology file using seapy as:

```
seapy.roms.interp.to_clim(base_dir + "hycom_file.nc",
                          dest_file=base_dir + "my_clim.nc",
                          dest_grid=mygrid, nx=1/25., ny=1/25.,
                          vmap={"zeta":"zeta", "temp":"temp",
                          "u":"u", "v":"v", "salt":"salt"})
```

Strangely, an ncdump of the climatology file reveals the first couple of lines of data (near the masked data) for ubar and v_bar have some extreme values (e.g., -54,000). Does anyone have any idea of what I might be doing wrong?

**Comment by powellb** [comment]
This means it is extrapolating data. It can only interpolate. 

-Brian

**Comment by ForTozs** [comment]
Thanks. So would a difference in land masks due to resolution be a potential cause of this?
