### ISSUE TITLE
seapy/lib.py

### ISSUE THREAD

**Issue by ivicajan** [powellb/seapy#56]
should have in line 25 
_default_timeref = "days since " + default_epoch.strftime("%Y-%m-%d %H:%M:%S")
instead 
_default_timeref = "days since " + default_epoch.strftime("%Y-%m-%m %H:%M:%S")

You have %m and should be %d for day ... 
Ivica

P.S. Not sure if you have it on other places as well

**Comment by powellb** [comment]
Thank you for the comment. Corrected in tag 0.3.1
