### ISSUE TITLE
tide.py and new numpy

### ISSUE THREAD

**Issue by ivicajan** [powellb/seapy#57]
in tide.py you should add option for pickle to be compatable with numpy 1.17+
line 25 I think:
with np.load(os.path.dirname(__file__) + "/constituents.npz", allow_pickle=True) as data:

otherwise install via conda is not working (if having updated numpy)

Cheers
Ivica

**Comment by powellb** [comment]
Thanks, sorry for the delay.

This has been incorporated into tagged release 0.4.1.
