### ISSUE TITLE
 No module named 'seapy.external'

### ISSUE THREAD

**Issue by huyquangtranaus** [powellb/seapy#65]
Hi,

Is there any suggestion to fix the following error message:

"/home/hugo/Pyroms_roms/seapy/seapy/oa.py", line 13, in <module>
    from seapy.external import oalib
ModuleNotFoundError: No module named 'seapy.external'

Thanks 
Huy

**Comment by powellb** [comment]
Actually (I didn't write the Readme), what you did (and the Readme) are correct. The `pip install -e` option uses the local copy you downloaded...
